apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: saidblb
  name: saidblb
  namespace: sai-ns
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: saidblb
  type: ClusterIP
status:
  loadBalancer: {}
